local file_types = {
  "bash",
  "c",
  "cpp",
  "css",
  "dockerfile",
  "git_config",
  "git_rebase",
  "gitcommit",
  "gitignore",
  "go",
  "graphql",
  "hcl",
  "html",
  "javascript",
  "jq",
  "jsdoc",
  "json",
  "json5",
  "lua",
  "markdown",
  "markdown_inline",
  "mermaid",
  "proto",
  "python",
  "query",
  "regex",
  "ruby",
  "scss",
  "soql",
  "sql",
  "ssh_config",
  "tcl",
  "terraform",
  "toml",
  "tsx",
  "typescript",
  "vim",
  "vimdoc",
  "xml",
  "yaml",
  "zsh",
}

-- Parsers to install:
require('nvim-treesitter').install(file_types)

vim.api.nvim_create_autocmd('FileType', {
    -- Filetypes to run autocmd on:
    -- pattern = file_types,
    pattern = {
      "bash",
      "c",
      "cpp",
      "css",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "go",
      "graphql",
      "hcl",
      "html",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "lua",
      "markdown",
      "markdown_inline",
      "mermaid",
      "proto",
      "python",
      "query",
      "regex",
      "ruby",
      "scss",
      "soql",
      "sql",
      "ssh_config",
      "tcl",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "zsh",
    },
    callback = function()
      -- Enables syntax highlighting:
      vim.treesitter.start()
      -- Enables treesitter-based folding:
      -- vim.wo[0][0].foldexpr = 'v:lua.vim.treesitter.foldexpr()'
      -- vim.wo[0][0].foldmethod = 'expr'
      -- Enables experimental treesitter-based indentation:
      vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
      end,
})
