# [font.BigBlueTerm437]
[font]
size = 14.0

[font.bold]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Regular"
