# FiraMono Nerd Font Mono
[font]
size = 18.0

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"
