# Hasklug Nerd Font Mono
[font]
size = 18.0

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"
