# JetBrains Mono Nerd Font
[font]
size = 14.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"
