# Monocraft Nerd Font
[font]
size = 14.0

[font.bold]
family = "Monocraft Nerd Font"
style = "Bold"

[font.italic]
family = "Monocraft Nerd Font"
style = "Italic"

[font.normal]
family = "Monocraft Nerd Font"
style = "Book"
