# Mononoki Nerd Font
[font]
size = 18.0

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

