# ShureTechMono Nerd Font Mono
[font]
size = 14.0

[font.bold]
family = "ShureTechMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "ShureTechMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font Mono"
style = "Regular"

