# Terminess Nerd Font Mono
[font]
size = 22.0

[font.bold]
family = "Terminess Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Terminess Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"

